---
title: "Heritability results"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---

# Set-up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, eval = FALSE)

# Define & load the packages
packages <- c("dplyr", "magrittr", "ggplot2", "ggridges", "MasterBayes", "mvtnorm", "MASS", "MCMCglmm", "pedtricks", "pedigree", "purrr") 

# Install packages not yet installed - change lib to library path
# installed_packages <- packages %in% rownames(installed.packages())
# 
#  if (any(installed_packages == FALSE)) {
#   install.packages(packages[!installed_packages])
# }

invisible(lapply(packages, library, character.only = TRUE))

## Suppress dplyr summarise warning
options(dplyr.summarise.inform = FALSE)

## Make sure using dplyr select
select <- dplyr::select

# Set colours
col_effort <- "#1b9e77"
col_bearing <- "#aaf0db"
col_slope <- "#0d4e3a"
col_used <- "#3cddac"

source("RPT_functions.R")

```

# Pedigree summary

```{r summarise_pedigrees}

pedigree_list <- list(
  bbal_birdis = "Data_inputs/bbal_birdis_pedigree.csv",
  waal_birdis = "Data_inputs/waal_birdis_pedigree.csv",
  waal_cro    = "Data_inputs/waal_cro_pedigree.csv" )

master_pedigree <- map_df(pedigree_list, function(path) {
  read.csv(path) %>%
    mutate(across(any_of(c("id", "dam", "sire")), as.character)) }, .id = "population") %>%
  select(-any_of("Year")) %>%
  mutate(across(c(dam, sire), ~na_if(., "0")))

## Fix birds - sires encoded as 0, birds recorded as both dams and sires
master_pedigree$sire[master_pedigree$id == "1271009"] <- "1318880"
master_pedigree$dam[master_pedigree$id == "1271009"] <- "1318939"

master_pedigree$sire[master_pedigree$id == "1434383"] <- "1139670"
master_pedigree$dam[master_pedigree$id == "1434383"] <- "1146056"

master_pedigree$sire[master_pedigree$id == "4003739"] <- "5116152"
master_pedigree$dam[master_pedigree$id == "4003739"] <- "5142862"

master_pedigree$sire[master_pedigree$id == "4003674"] <- "4000720"
master_pedigree$dam[master_pedigree$id == "4003674"] <- "5110290"

master_pedigree$sire[master_pedigree$id == "5144330"] <- "5093486"
master_pedigree$dam[master_pedigree$id == "5144330"] <- "5097831"


spec_col <- c("bbal_birdis", "waal_birdis", "waal_cro")
summary.table <- vector(mode = "list", length = length(spec_col))

for (i in 1:length(spec_col)) {
  
  ped <- master_pedigree %>% filter(population == spec_col[i]) %>% select(-population)
  order_ped <- MasterBayes::orderPed(ped)
  depths = countGen(order_ped)
  
  df <- data.frame(
    N              = nrow(order_ped),
    founders       = sum(is.na(order_ped$sire) & is.na(order_ped$dam)),
    pct_paternal   = round(sum(!is.na(order_ped$sire)) / nrow(order_ped) * 100, 1),
    pct_maternal   = round(sum(!is.na(order_ped$dam)) / nrow(order_ped) * 100, 1),
    gen_depth_mean = round(mean(depths), 2),
    gen_depth_max  = max(depths),
    population     = spec_col[i])
  
  summary.table[[i]] <- df
  
}

table_s2 <- do.call("rbind", summary.table)
save(table_s2, file = "Data_outputs/table_s2_data.RData")

```


# Power analysis

```{r power_analysis}

# CHANGE THIS BIT TO CYCLE THROUGH EACH COLONY #

focal_pop <- "waal_cro" # bbal_birdis  waal_birdis   waal_cro
my_species <- strsplit(focal_pop, "_")[[1]][1]
my_colony <- strsplit(focal_pop, "_")[[1]][2]

# Load data ====

load("Data_inputs/behavioural_repeatability_data.RData")

focal.dat <- rep_data %>% filter(species == my_species & colony == my_colony)
pedigree.df <- read.csv(paste0("Data_inputs/", focal_pop, "_pedigree.csv"))# %>% select(-Year)

## Fix some dam/sire encoding
pedigree.df$sire[pedigree.df$sire == "0"] <- NA

pedigree.df$sire[pedigree.df$id == "1271009"] <- "1318880"
pedigree.df$dam[pedigree.df$id == "1271009"] <- "1318939"

pedigree.df$sire[pedigree.df$id == "1434383"] <- "1139670"
pedigree.df$dam[pedigree.df$id == "1434383"] <- "1146056"

pedigree.df$sire[pedigree.df$id == "4003739"] <- "5116152"
pedigree.df$dam[pedigree.df$id == "4003739"] <- "5142862"

pedigree.df$sire[pedigree.df$id == "4003674"] <- "4000720"
pedigree.df$dam[pedigree.df$id == "4003674"] <- "5110290"

pedigree.df$sire[pedigree.df$id == "5144330"] <- "5093486"
pedigree.df$dam[pedigree.df$id == "5144330"] <- "5097831"

## Check pedigree in correct format
pedigree.df <- fix_ped(pedigree.df)
pedigree.df <- orderPed(pedigree.df)

## Check for > 2 parents
pedigree.df %>%
  group_by(id) %>%
  summarise(n_parents = n_distinct(c(dam, sire), na.rm = TRUE)) %>%
  filter(n_parents > 2)

## Prune to used dataset
pedigree_pruned <- prune_pedigree(focal.dat, pedigree.df)
#pedigree_pruned <- pedigree.df

#draw_ped(pedigree_pruned)


# Simulate genetic analyis ====

# Set parameters
VA <- seq(from=0.0, to =0.3, by=0.02)
nrep <- 200

## Make inverse genetic matrix
ainv <- inverseA(pedigree_pruned)

## Create output wrapper
all_va_results <- data.frame(VA = numeric(),
                             rep = integer(),
                             posterior = numeric(),
                             cilow = numeric(),
                             cihigh = numeric())

## Set progress bar
n_total <- length(VA) * nrep
pb <- txtProgressBar(min = 0, max = n_total, style = 3)
counter <- 0

for (i in 1:length(VA))  {
    
    print(paste0("Processing VA: ", VA[i], " (", i, " of ", length(VA), ")"))
  
    va_results <- expand.grid(VA=VA[i], rep=1:nrep, posterior=NA, cilow=NA, cihigh=NA)

    for(k in 1:nrep){
       
      xP <- phen_sim(pedigree_pruned, traits = 1, randomA = VA[i]*diag(1), randomE = (1-VA[i])*diag(1), verbose = F)[[1]]
      
      # wrap the MCMCglmm fit in tryCatch
      fit <- tryCatch({
        m0sim <- MCMCglmm(data = xP,
                          fixed = trait_1 ~ 1,
                          random =~ id,
                          ginverse = list(id = ainv$Ainv),
                          verbose = FALSE)
        
        h2 <- m0sim$VCV[,1] / (m0sim$VCV[,1] + m0sim$VCV[,2])
        
        c(median(h2), HPDinterval(h2)[1], HPDinterval(h2)[2])
        
      }, error = function(e) {
        # return NAs if it fails
        c(NA, NA, NA)
      })
      
      va_results[va_results$rep == k, c("posterior","cilow","cihigh")] <- fit
      
      ## Update progress bar
      counter <- counter + 1
      setTxtProgressBar(pb, counter)
    
    }
   
    all_va_results <- rbind(all_va_results, va_results)
  
  }

save(all_va_results, file = paste0("Data_outputs/", focal_pop, "_heritability_power_analysis2.RData"))

ggplot(all_va_results, aes(x=VA, y=posterior)) + 
  geom_point() 

ggplot(all_va_results, aes(x=VA, y=cilow)) + 
  geom_point() 

all_va_results %>% 
  group_by(VA) %>%
  summarise(coverage=mean(VA<=cihigh & VA>=cilow, na.rm = T), 
            power=mean(cilow>=quantile(all_va_results$posterior[all_va_results$VA==0], probs = 0.975), na.rm = T))

# Another way of summarising power
all_va_results %>% group_by(VA) %>%
  summarise(coverage=mean(VA<=cihigh & VA>=cilow, na.rm = T), power=mean(cilow>= all_va_results$posterior[all_va_results$VA==0], na.rm = T))

```

# Combine posteriors

```{r combine_posteriors}

# Foraging effort ====

posteriors_effort <- loadRData("Data_outputs/behaviour_heritability_posteriors.RData")

## Recode behaviour & spec col
posteriors_effort %<>%
  mutate(behaviour = recode(behaviour,
                            "duration.hrs" = "Trip duration",
                            "landings_per_day" = "Landings per day",
                            "transit_time.pct" = "Flight time",
                            "rest_time.pct" = "Rest time",
                            "transit_to_rest.ratio" = "Flight:Rest ratio"),
          spec_col = recode(spec_col,
                "bbal_birdis" = "BBAL Bird Island",
                "waal_birdis" = "WAAL Bird Island",
                "waal_cro" = "WAAL Crozet"),
         behaviour = factor(behaviour, levels = rev(c("Trip duration", "Rest time", "Landings per day", "Flight:Rest ratio", "Flight time"))))


# Foraging bearings ====

posteriors_bearings <- loadRData("Data_outputs/all_posteriors_spatial_heritability.RData")


# Habitat used ====

bbal_birdis.used <- loadRData("Data_outputs/bbal_birdis_habitat_used_h2_posteriors.RData") %>% mutate(spec_col = "BBAL Bird Island")
waal_birdis.used <- loadRData("Data_outputs/waal_birdis_habitat_used_h2_posteriors.RData") %>% mutate(spec_col = "WAAL Bird Island")
waal_cro.used <- loadRData("Data_outputs/waal_cro_habitat_used_h2_posteriors.RData") %>% mutate(spec_col = "WAAL Crozet")

posteriors_used <- rbind(bbal_birdis.used, waal_birdis.used, waal_cro.used)


# Habitat slopes =====

bbal_birdis.slopes <- loadRData("Data_outputs/bbal_birdis_habitat_pref_h2_posteriors.RData") %>% mutate(spec_col = "BBAL Bird Island")
waal_birdis.slopes <- loadRData("Data_outputs/waal_birdis_habitat_pref_h2_posteriors.RData") %>% mutate(spec_col = "WAAL Bird Island")
waal_cro.slopes <- loadRData("Data_outputs/waal_cro_habitat_pref_h2_posteriors.RData") %>% mutate(spec_col = "WAAL Crozet")

posteriors_slopes <- rbind(bbal_birdis.slopes, waal_birdis.slopes, waal_cro.slopes)




# Bind the behaviours into one plot ====

posteriors_effort %<>%
  select(c(spec_col, h2_post, behaviour)) %>%
  rename(h2 = h2_post) %>%
  mutate(group = "effort")

posteriors_bearings %<>%
  select(c(spec_col, h2)) %>%
  mutate(behaviour = "Foraging bearing",
         group = "bearings")

posteriors_slopes %<>%
  rename(behaviour = env) %>%
  mutate(behaviour = paste0(behaviour, " preference"),
         group = "slopes") %>%
  relocate(c(spec_col, h2), .before = behaviour) %>%
  mutate(behaviour = factor(
    behaviour,
    levels = rev(c("Bathymetry preference", "Chlorophyll preference", "SST preference"))))

posteriors_used %<>%
  rename(behaviour = env) %>%
  mutate(behaviour = paste0(behaviour, " used"),
         group = "used") %>%
  relocate(c(spec_col, h2), .before = behaviour) %>%
  mutate(behaviour = factor(
    behaviour,
    levels = rev(c("Bathymetry used", "Chlorophyll used", "SST used"))))

posteriors_all <- rbind(posteriors_effort, posteriors_bearings, posteriors_used, posteriors_slopes) 

# Change ordering for plot/table
posteriors_all %<>%
   mutate(behaviour = factor(behaviour, 
                             levels = c("Trip duration", "Rest time", "Landings per day", "Flight:Rest ratio", "Flight time",
                                        "Foraging bearing",
                                        "Bathymetry used", "Chlorophyll used", "SST used",
                                        "Bathymetry preference", "Chlorophyll preference", "SST preference"))) %>%
   arrange(spec_col, behaviour)

posteriors_all$behaviour <- factor(
  posteriors_all$behaviour,
  levels = rev(levels(posteriors_all$behaviour)))

save(posteriors_all, file = "Data_outputs/heritability_posteriors_all.RData")

```


